@Host: http://localhost:5054


POST {{Host: }}/auth/register
Content-Type: application/json

{
    "firstName": "Chico",
    "lastName": "Rangel",
    "email": "chicorangel@gmail.com",
    "password": "$$$$$$"
}
